name: agro_control_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- AQUI ES DONDE DEBEN IR LAS LIBRERIAS ---
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0       # El motor del mapa (Gratis)
  latlong2: ^0.9.0          # Para manejar coordenadas
  geolocator: ^13.0.0
  firebase_core: ^3.1.0     # <--- FALTA ESTA (El núcleo de Firebase)
  cloud_firestore: ^5.0.0   # <--- Y ESTA (La base de datos)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Todo lo que estaba abajo (fonts, assets) va aquí, 
  # pero NO las dependencias.